sudo: false
language: cpp
compiler:
  - gcc
install:
  - export CXX="g++-4.8" CC="gcc-4.8"
  - alias gcc='gcc-4.8'
  - alias cc='gcc-4.8'
  - alias g++='g++-4.8'
  - alias c++='c++-4.8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
